?start: program

program: stmt "."?

?stmt   : general_stmt
        | domain_stmt
        | def_stmt

?general_stmt   : stmt _SEP stmt -> stmt
                |  IDENT _WS "is" _WS expr -> asign
                | ("say" | "print" | "output") _WS expr -> print
                | ("return") _WS expr -> return

?def_stmt   : expr _WS "is" _WS expr -> asign
            | expr _WS "is" _WS "a" _WS TYPE _WS expr? -> assig_type

?domain_stmt    : "go to" _WS expr
                | ("make" | "create") NEW? _WS "file" _WS expr _WS "in" _WS expr -> make_file
                | ("make" | "create") NEW? _WS "folder" _WS expr _WS "in" _WS expr -> make_folder
                | "rename" _WS expr _WS "to" _WS expr
                | "delete" _WS expr
                | "copy from" _WS expr _WS "to" _WS expr

?expr   :or_expr    


?or_expr    : and_expr
            | or_expr (_WS? "||" _WS? | _WS "or" _WS) and_expr -> or

?and_expr   : eq_expr
            | and_expr (_WS? "&&" _WS? | _WS "and" _WS) eq_expr -> and 


?eq_expr    : rel_expr
            | eq_expr (_WS?"=="_WS? | _WS "equals" _WS) rel_expr -> eq


?rel_expr   : plus_expr
            | rel_expr (_WS? "!=" _WS?| _WS "not equals" _WS) plus_expr         -> neq
            | rel_expr (_WS? ">" _WS? | _WS "greater than" _WS) plus_expr       -> gt
            | rel_expr (_WS? "<" _WS? | _WS "less than" _WS) plus_expr          -> lt
            | rel_expr (_WS? ">=" _WS?| _WS "greater or equal" _WS) plus_expr   -> gte
            | rel_expr (_WS? "<=" _WS?| _WS "less or equal" _WS) plus_expr      -> lte
    

?plus_expr  : mult_expr
            | plus_expr (_WS?"+"_WS?|_WS "plus" _WS) mult_expr -> plus
            | plus_expr (_WS?"-"_WS?| _WS "minus" _WS) mult_expr -> minus


?mult_expr  :unary_expr
            | mult_expr (_WS? "*" _WS? | _WS "times" _WS) unary_expr -> mult
            | mult_expr (_WS? "/" _WS?| _WS "divided by" _WS) unary_expr -> div
            | mult_expr (_WS? "%" _WS?| _WS "mod" _WS) unary_expr -> mod

?unary_expr : access_expr
            | ("not" _WS | "!" _WS?| "negative" _WS | "neg" _WS) unary_expr -> not
            | "length of" _WS access_expr -> length
            | "first element of" _WS access_expr -> first
            | "last element of"  _WS access_expr -> last

    // chech up on 
?access_expr    : term
                | access_expr _WS "at index" _WS access_expr -> list_look
                | access_expr _WS "regex" _WS access_expr -> regex
                | access_expr _WS "age" -> age
                // unit needs to be looked into. I don't think it fits here.
                | access_expr _WS unit ->unit



// conflict: func and var. both can be reduced to IDENT.    
?term   : IDENT  -> var
        | IDENT  (_WS "result" )? _WS "using" _WS  ("(" _WS* expr ("," _WS* expr)* ")" | term) -> func
        | NUMBER -> number
        | FLOAT  -> decimal
        | STRING -> text
        | BOOLEAN -> boolean
        | "null" -> null
        | "now"  -> now
        | "here" -> here
        |"("_WS* expr _WS*")" -> paren
 
TYPE    : "text"
        | "number"
        | "decimal"
        | "boolean"
        | "date" 
        | "time" 
        | "list"
        | "folder" 
        | "file"


unit    : "second" -> second
        | "minute" -> minute
        | "hour"   -> hour
        | "day"    -> day
        | "month"  -> month
        | "year"   -> year

NEW : _WS "new"

_SEP: "." _WS+| (_WS* _NL)+ | "." (_WS* _NL)+
COMMENT: /#[^\n]*/
_WS: " "
BOOLEAN: "true" | "false"
%import common.NEWLINE -> _NL
%import common.INT -> NUMBER
%import common.FLOAT -> FLOAT
%import common.ESCAPED_STRING -> STRING
IDENT: /[A-Z][a-zA-Z0-9]*/(" "*/[A-Z][a-zA-Z0-9]*/)*
%ignore COMMENT