?start: program

program: stmt "."?

?stmt: general_stmt

?general_stmt   : stmt _SEP stmt -> stmt
                |  IDENT _WS "is" _WS expr -> asign
                | ("say" | "print" | "output") _WS expr -> print
                | ("return") _WS expr -> return

?domain_stmt: "go to" _WS expr 

?expr: or_expr

?or_expr    : and_expr
            | or_expr (_WS? "||" _WS? | _WS "or" _WS) and_expr -> or

?and_expr   : eq_expr
            | and_expr (_WS? "&&" _WS? | _WS "and" _WS) eq_expr -> and 

?eq_expr    : rel_expr
            | eq_expr (_WS?"=="_WS? | _WS "equals" _WS) rel_expr -> eq

?rel_expr   : plus_expr
            | rel_expr (_WS? "!=" _WS?| _WS "not equals" _WS) plus_expr         -> neq
            | rel_expr (_WS? ">" _WS? | _WS "greater than" _WS) plus_expr       -> gt
            | rel_expr (_WS? "<" _WS? | _WS "less than" _WS) plus_expr          -> lt
            | rel_expr (_WS? ">=" _WS?| _WS "greater or equal" _WS) plus_expr   -> gte
            | rel_expr (_WS? "<=" _WS?| _WS "less or equal" _WS) plus_expr      -> lte

?plus_expr  : mult_expr
            | plus_expr (_WS?"+"_WS?|_WS "plus" _WS) mult_expr -> plus
            | plus_expr (_WS?"-"_WS?| _WS "minus" _WS) mult_expr -> minus
    
?mult_expr  :unary_expr
            | mult_expr (_WS? "*" _WS? | _WS "times" _WS) unary_expr -> mult
            | mult_expr (_WS? "/" _WS?| _WS "divided by" _WS) unary_expr -> div
            | mult_expr (_WS? "%" _WS?| _WS "mod" _WS) unary_expr -> mod

?unary_expr : access_expr
            | ("not" _WS | "!" _WS?| "negative" _WS | "neg" _WS) unary_expr -> not
            | "("_WS* expr _WS*")" -> paren
    
// conflict: func and var,    
?access_expr    : term 
                |IDENT  (_WS ("result" )? _WS "using" _WS  ("(" _WS* expr ("," _WS* expr)* ")" | expr) ) -> func

?term   :IDENT -> var
        | NUMBER
        | STRING
        | "true"
        | "false"
        | "null"
        | "now"
        | "here"

TYPE: "int" | "string" | "bool" | "null"

_SEP: "." _WS+| (_WS* _NL)+ | "." (_WS* _NL)+

_WS: " "
%import common.NEWLINE -> _NL
%import common.INT -> NUMBER
%import common.ESCAPED_STRING -> STRING
IDENT: /[A-Z][a-zA-Z0-9]*/(" "*/[A-Z][a-zA-Z0-9]*/)*