?start: program

program: stmt "."?

?stmt   : stmt _SEP stmt    -> stmt
        | general_stmt
        | domain_stmt
        | def_stmt

?general_stmt   : stmt ("else" | "otherwise") stmt  -> if_unable
                | "if" expr ":" block (_NL*( "else"|"otherwise") ":"? block)?  -> if_else
                //why is ("in" expr) removable?
                | ("for all" | "for each") IDENT ("in" expr)? ":"? block -> for_all
                | "repeat until" expr block -> repeat
                | ("stop" | "quit") -> quit
                | ("say" | "print" | "output") expr -> print
                | ("return") expr   -> return
                // I dont know what this is.
                | "add" expr "to" expr -> add_i_dont_know
                | "remove" expr "from" expr -> remove_i_dont_know





?def_stmt       : expr "is" expr -> asign
                | expr "is" "a" TYPE expr? -> assig_type
                |"new"? "task" IDENT "uses" (IDENT ("," IDENT)*)+":" block -> asign_func






?domain_stmt    : "go to" expr
                | ("make " | "create ") NEW? TYPE expr ("in" expr)? -> make
                | "rename" expr "to" expr
                | "delete" expr
                | "copy from" expr "to" expr

?expr   :or_expr    


?or_expr    : and_expr
            | or_expr ( "||"  | "or" ) and_expr -> or

?and_expr   : eq_expr
            | and_expr ( "&&"  | "and" ) eq_expr -> and 


?eq_expr    : rel_expr
            | eq_expr ("==" | "equals" ) rel_expr -> eq


?rel_expr   : plus_expr
            | rel_expr ( "!=" | "not equals" ) plus_expr         -> neq
            | rel_expr ( ">"  | "greater than" ) plus_expr       -> gt
            | rel_expr ( "<"  | "less than" ) plus_expr          -> lt
            | rel_expr ( ">=" | "greater or equal" ) plus_expr   -> gte
            | rel_expr ( "<=" | "less or equal" ) plus_expr      -> lte
    

?plus_expr  : mult_expr
            | plus_expr ("+"|"plus" ) mult_expr -> plus
            | plus_expr ("-"| "minus" ) mult_expr -> minus


?mult_expr  :unary_expr
            | mult_expr ( "*"  | "times" ) unary_expr -> mult
            | mult_expr ( "/" | "divided by" ) unary_expr -> div
            | mult_expr ( "%" | "mod" ) unary_expr -> mod

?unary_expr : access_expr
            | ("not" | "!" | "negative" | "neg" ) unary_expr -> not
            | "length of" access_expr -> length
            | "first element of" access_expr -> first
            | "last element of"  access_expr -> last

    // chech up on 
?access_expr    : term
                | access_expr "at index" access_expr -> list_look
                | access_expr "regex" access_expr -> regex
                | access_expr "age" -> age
                // unit needs to be looked into. I don't think it fits here and and can't do much as it is written.
                | access_expr unit ->unit



// conflict: func and var. both can be reduced to IDENT.    
?term   : IDENT  -> var
        //"func" has a "Reduce/Reduce collision" with "paren"
//        | IDENT  ("result" )? "using"  ("("  expr ("," expr)* ")" | term) -> func
        | NUMBER -> number
        | FLOAT  -> decimal
        | STRING -> text
        | BOOLEAN -> boolean
        | "null" -> null
        | "now"  -> now
        | "here" -> here
        |"(" expr ")" -> paren
        | TYPE
 
TYPE    : "text"
        | "number"
        | "decimal"
        | "boolean"
        | "date" 
        | "time" 
        | "list"
        | "folder" 
        | "file"


unit    : ("second" | "seconds") -> second
        | ("minute" | "minutes") -> minute
        | ("hour" | "hours")   -> hour
        | ("day" | "days")   -> day
        | ("month" | "months")  -> month
        | ("year" | "years")  -> year

NEW : "new"
_BLOCKSTART: "BLOCKSTART"
_BLOCKEND: "BLOCKEND"  
_SEP: "." _WS* _NL* |  _NL+
COMMENT: /#[^\n]*\n/
%import common.WS_INLINE -> _WS
BOOLEAN: "true" | "false"
%import common.NEWLINE -> _NL
%import common.INT -> NUMBER
%import common.FLOAT -> FLOAT
%import common.ESCAPED_STRING -> STRING
IDENT: /[A-Z][a-zA-Z0-9]*/(" "*/[A-Z][a-zA-Z0-9]*/)*
%ignore COMMENT
%ignore _WS


block : _NL _BLOCKSTART _NL stmt _NL _BLOCKEND
